// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRepos(t *testing.T) {
	t.Parallel()

	query := Repos()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testReposDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testReposQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Repos().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testReposSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RepoSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testReposExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RepoExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Repo exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RepoExists to return true, but got false.")
	}
}

func testReposFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	repoFound, err := FindRepo(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if repoFound == nil {
		t.Error("want a record, got nil")
	}
}

func testReposBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Repos().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testReposOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Repos().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testReposAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	repoOne := &Repo{}
	repoTwo := &Repo{}
	if err = randomize.Struct(seed, repoOne, repoDBTypes, false, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}
	if err = randomize.Struct(seed, repoTwo, repoDBTypes, false, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = repoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = repoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Repos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testReposCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	repoOne := &Repo{}
	repoTwo := &Repo{}
	if err = randomize.Struct(seed, repoOne, repoDBTypes, false, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}
	if err = randomize.Struct(seed, repoTwo, repoDBTypes, false, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = repoOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = repoTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func repoBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Repo) error {
	*o = Repo{}
	return nil
}

func repoAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Repo) error {
	*o = Repo{}
	return nil
}

func repoAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Repo) error {
	*o = Repo{}
	return nil
}

func repoBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Repo) error {
	*o = Repo{}
	return nil
}

func repoAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Repo) error {
	*o = Repo{}
	return nil
}

func repoBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Repo) error {
	*o = Repo{}
	return nil
}

func repoAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Repo) error {
	*o = Repo{}
	return nil
}

func repoBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Repo) error {
	*o = Repo{}
	return nil
}

func repoAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Repo) error {
	*o = Repo{}
	return nil
}

func testReposHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Repo{}
	o := &Repo{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, repoDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Repo object: %s", err)
	}

	AddRepoHook(boil.BeforeInsertHook, repoBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	repoBeforeInsertHooks = []RepoHook{}

	AddRepoHook(boil.AfterInsertHook, repoAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	repoAfterInsertHooks = []RepoHook{}

	AddRepoHook(boil.AfterSelectHook, repoAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	repoAfterSelectHooks = []RepoHook{}

	AddRepoHook(boil.BeforeUpdateHook, repoBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	repoBeforeUpdateHooks = []RepoHook{}

	AddRepoHook(boil.AfterUpdateHook, repoAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	repoAfterUpdateHooks = []RepoHook{}

	AddRepoHook(boil.BeforeDeleteHook, repoBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	repoBeforeDeleteHooks = []RepoHook{}

	AddRepoHook(boil.AfterDeleteHook, repoAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	repoAfterDeleteHooks = []RepoHook{}

	AddRepoHook(boil.BeforeUpsertHook, repoBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	repoBeforeUpsertHooks = []RepoHook{}

	AddRepoHook(boil.AfterUpsertHook, repoAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	repoAfterUpsertHooks = []RepoHook{}
}

func testReposInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testReposInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(repoColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRepoToManyCommits(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Repo
	var b, c Commit

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, commitDBTypes, false, commitColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, commitDBTypes, false, commitColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.RepoID = a.ID
	c.RepoID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Commits().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.RepoID == b.RepoID {
			bFound = true
		}
		if v.RepoID == c.RepoID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := RepoSlice{&a}
	if err = a.L.LoadCommits(ctx, tx, false, (*[]*Repo)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Commits); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Commits = nil
	if err = a.L.LoadCommits(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Commits); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testRepoToManyUsers(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Repo
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	_, err = tx.Exec("insert into \"user_repos\" (\"repo_id\", \"user_id\") values ($1, $2)", a.ID, b.ID)
	if err != nil {
		t.Fatal(err)
	}
	_, err = tx.Exec("insert into \"user_repos\" (\"repo_id\", \"user_id\") values ($1, $2)", a.ID, c.ID)
	if err != nil {
		t.Fatal(err)
	}

	check, err := a.Users().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ID == b.ID {
			bFound = true
		}
		if v.ID == c.ID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := RepoSlice{&a}
	if err = a.L.LoadUsers(ctx, tx, false, (*[]*Repo)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Users); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Users = nil
	if err = a.L.LoadUsers(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Users); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testRepoToManyAddOpCommits(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Repo
	var b, c, d, e Commit

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, repoDBTypes, false, strmangle.SetComplement(repoPrimaryKeyColumns, repoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Commit{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, commitDBTypes, false, strmangle.SetComplement(commitPrimaryKeyColumns, commitColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Commit{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCommits(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.RepoID {
			t.Error("foreign key was wrong value", a.ID, first.RepoID)
		}
		if a.ID != second.RepoID {
			t.Error("foreign key was wrong value", a.ID, second.RepoID)
		}

		if first.R.Repo != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Repo != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Commits[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Commits[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Commits().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testRepoToManyAddOpUsers(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Repo
	var b, c, d, e User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, repoDBTypes, false, strmangle.SetComplement(repoPrimaryKeyColumns, repoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*User{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*User{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddUsers(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if first.R.Repos[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}
		if second.R.Repos[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}

		if a.R.Users[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Users[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Users().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testRepoToManySetOpUsers(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Repo
	var b, c, d, e User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, repoDBTypes, false, strmangle.SetComplement(repoPrimaryKeyColumns, repoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*User{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetUsers(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Users().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetUsers(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Users().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	// The following checks cannot be implemented since we have no handle
	// to these when we call Set(). Leaving them here as wishful thinking
	// and to let people know there's dragons.
	//
	// if len(b.R.Repos) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	// if len(c.R.Repos) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	if d.R.Repos[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}
	if e.R.Repos[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}

	if a.R.Users[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Users[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testRepoToManyRemoveOpUsers(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Repo
	var b, c, d, e User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, repoDBTypes, false, strmangle.SetComplement(repoPrimaryKeyColumns, repoColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*User{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddUsers(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Users().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveUsers(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Users().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if len(b.R.Repos) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if len(c.R.Repos) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if d.R.Repos[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Repos[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if len(a.R.Users) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Users[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Users[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testReposReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testReposReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RepoSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testReposSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Repos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	repoDBTypes = map[string]string{`ID`: `integer`, `Name`: `text`, `Owner`: `text`}
	_           = bytes.MinRead
)

func testReposUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(repoPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(repoAllColumns) == len(repoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, repoDBTypes, true, repoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testReposSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(repoAllColumns) == len(repoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Repo{}
	if err = randomize.Struct(seed, o, repoDBTypes, true, repoColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, repoDBTypes, true, repoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(repoAllColumns, repoPrimaryKeyColumns) {
		fields = repoAllColumns
	} else {
		fields = strmangle.SetComplement(
			repoAllColumns,
			repoPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RepoSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testReposUpsert(t *testing.T) {
	t.Parallel()

	if len(repoAllColumns) == len(repoPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Repo{}
	if err = randomize.Struct(seed, &o, repoDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Repo: %s", err)
	}

	count, err := Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, repoDBTypes, false, repoPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Repo struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Repo: %s", err)
	}

	count, err = Repos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
